# Generated by Django 5.2.3 on 2025-07-02 01:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diabetic', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctor',
            name='email',
            field=models.EmailField(max_length=254, unique=True),
        ),
    ]
