# Generated by Django 5.2.3 on 2025-07-02 02:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diabetic', '0002_alter_doctor_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='password',
            field=models.CharField(default='1234'),
        ),
    ]
