# Generated by Django 5.2.3 on 2025-07-02 03:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diabetic', '0003_patient_password'),
    ]

    operations = [
        migrations.CreateModel(
            name='EducationalContent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('file', models.FileField(upload_to='educational_files/')),
                ('file_type', models.CharField(choices=[('document', 'Document'), ('video', 'Video'), ('audio', 'Audio')], max_length=20)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='diabetic.doctor')),
            ],
        ),
    ]
