# Generated by Django 5.2.3 on 2025-07-04 20:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diabetic', '0004_educationalcontent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctor',
            name='password',
            field=models.CharField(),
        ),
        migrations.AlterField(
            model_name='patient',
            name='password',
            field=models.CharField(),
        ),
    ]
