# Generated by Django 5.2.3 on 2025-07-04 23:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diabetic', '0005_alter_doctor_password_alter_patient_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(max_length=254, unique=True, verbose_name='email address'),
        ),
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True),
        ),
    ]
